linters:
  enable-all: true
  disable:
    # linters disabled in CAPI
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - lll
    - godox
    - wsl
    - whitespace
    - gocognit
    - gomnd
    - interfacer
    - godot
    - goerr113
    - nestif
    # linters disabled in this repo
    - gci
    - gofumpt
    - exhaustivestruct
    - nolintlint
    - nlreturn
    - wrapcheck
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  # List of regexps of issue texts to exclude, empty list by default.
  exclude:
    - Using the variable on range scope `(tc)|(rt)|(tt)|(test)|(testcase)|(testCase)` in function literal
    - "G108: Profiling endpoint is automatically exposed on /debug/pprof"
run:
  timeout: 10m
  skip-files:
    - "zz_generated.*\\.go$"
    - ".*conversion.*\\.go$"
