name: Byoh controller tests

on:
  pull_request:
    branches: [ main ]

jobs:

  test-byoh-controller:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install ginkgo
      run: sudo apt-get install golang-ginkgo-dev

    - name: test byoh controllers
      run: make controller-test